# Generated by Django 6.0.3 on 2026-04-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "heading",
                    models.CharField(
                        help_text="Введите наименование заголовка", max_length=100, verbose_name="Заголовок:"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Введите основной текст статьи", null=True, verbose_name="Содержимое"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите изображения",
                        null=True,
                        upload_to="blogs/",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("publication_attribute", models.BooleanField(default=True, verbose_name="Публикация")),
                (
                    "quantity_views",
                    models.IntegerField(
                        default=0, help_text="Количество просмотров", verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "ordering": ["heading", "content"],
            },
        ),
    ]
