# Generated by Django 6.0.3 on 2026-04-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории",
                        max_length=100,
                        verbose_name="Наименование категории",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание категории",
                        null=True,
                        verbose_name="Описание категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование продукта", max_length=100, verbose_name="Наименование продукта"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание продукта", null=True, verbose_name="Описание продукта"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите изображения",
                        null=True,
                        upload_to="products/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        blank=True, help_text="Введите цену за покупку", null=True, verbose_name="цена за покупку"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name", "description"],
            },
        ),
    ]
