# Generated by Django 6.0.4 on 2026-05-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Наименование продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="products/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="цена за покупку"),
        ),
    ]
